#include "IAlpacaCamV1.h"

using namespace Alpaca;
using namespace Alpaca::Camera;

IAlpacaCamV1::IAlpacaCamV1(unsigned int deviceNum, std::string deviceName)
	: AlpacaDeviceV1(AlpacaDeviceV1::DeviceTypeID::Camera, deviceNum, deviceName)
	, m_bayerOffsetX(0)
	, m_bayerOffsetY(0)
	, m_binX(0)
	, m_binY(0)
	, m_cameraState(CameraStateID::CameraIdle)
	, m_cameraXSize(0)
	, m_cameraYSize(0)
	, m_canAbortExposure(false)
	, m_canAsymmetricBin(false)
	, m_canFastReadout(false)
	, m_canGetCoolerPower(false)
	, m_canPulseGuide(false)
	, m_canSetCCDTemp(false)
	, m_canStopExposure(false)
	, m_CCDTemp(0.0)
	, m_coolerOn(false)
	, m_coolerPower(0.0)
	, m_electrosPerAdu(0.0)
	, m_exposureMin(0.0)
	, m_exposureMax(0.0)
	, m_eposureResolution(0.0)
	, m_fastReadout(false)
	, m_fullWellCapacity(0.0)
	, m_gain(0)
	, m_gainMax(0)
	, m_gainMin(0)
	, m_gains()
	, m_hasShutter(false)
	, m_heatsinkTemp(0.0)
	, m_imageReady(false)
	, m_isPulseGuiding(false)
	, m_lastExposureDuration(0.0)
	, m_lastExposureStartTime()
	, m_maxADU(0)
	, m_maxBinX(0)
	, m_maxBinY(0)
	, m_numX(0)
	, m_numY(0)
	, m_offset(0)
	, m_offsetMin(0)
	, m_offsetMax(0)
	, m_offsets()
	, m_percentComplete(0)
	, m_pixelSizeX(0.0)
	, m_pixelSizeY(0.0)
	, m_readoutMode(0)
	, m_readoutModes()
	, m_sensorName()
	, m_sensorType(SensorTypeID::Mono)
	, m_coolerSetpoint(0.0)
	, m_startX(0)
	, m_startY(0)
	, m_subExposureDuration(0.0)
	, m_pImageArrayI16(nullptr)
	, m_pImageArrayI32(nullptr)
	, m_pImageArrayF64(nullptr)
{}	 

IAlpacaCamV1::~IAlpacaCamV1()
{
}
